### ISSUE TITLE
Adding a Mute (speaker) relay

### ISSUE THREAD

**Issue by ayush-tanna** [judilsteve/MotorisedVolumeKnob#2]
Hi, Thanks for this wonderful effort.
I have added code to make a pin control a speaker relay to act as a mute switch from the remote. This relay should remain closed on power on and when required opened with a remote button - the same acting a toggle to switch it back on. Also when muted either of the Volume Up or Down buttons should close the relay.
[iR-Mute.zip](https://github.com/judilsteve/MotorisedVolumeKnob/files/9300660/iR-Mute.zip)
Unfortunately it is not working. Please help.

**Comment by judilsteve** [comment]
You're on the right track, but I don't think you've quite grokked how the `State<T>` classes work. Here's a simplified model of the state machine (with your mute state added). There's a couple transitions here that I haven't bothered to draw (e.g. jumping straight from the braking state to the vol-/vol+ state) but it's detailed enough for explanatory purposes:

![image](https://user-images.githubusercontent.com/4328790/184098127-15f55c20-07f4-4fa3-82e2-038f11b20477.png)

If you're not familiar with state machines, they are basically just [directed graphs](https://en.wikipedia.org/wiki/Directed_graph). The vertices (circles) are the possible states that the machine can be in (idle, volume increasing, braking, muted, etc), and the edges (arrows) are the possible transitions between those states. State machines typically operate in discrete cycles known as "ticks". During each tick, the state machine decides (based on what's going on in the world and what state it is currently in) whether it will move to a different state, or stay in the same state.

In my representation of a state machine, each state is represented by a subclass of the `State` class. Every tick, the current state's `Tick` function is called. Whatever is returned by that function will be the new state of the state machine for the next tick. This is certainly not the only way to implement a state machine, and I'm not even sure it's a *good* way to implement a state machine, but it seemed like a reasonable enough idea at the time.

Anyway, let's look at the `Tick` function for `IdleMotorState`:

```c++
MotorStateId const Tick(unsigned long const)
{
    IrPacket packet;
    if (irReceiver.TryGetPacket(packet) && !packet.IsRepeat)
    {
        if (packet.Code == config.VolumeUpCode) return VOLUME_INCREASING;
        else if (packet.Code == config.VolumeDownCode) return VOLUME_DECREASING;
    }
    return IDLE;
}
```

This function defines the logic that we should follow while we are in the idle state. What it says is:

 - If the volume up button was pressed, move to the `VOLUME_INCREASING` state
 - If the volume down button was pressed, move to the `VOLUME_DECREASING` state
 - Otherwise, stay in the `IDLE` state.

In essence, each of the return values inside a state's Tick function represents one of the edges *leaving* that state's vertex in the directed graph (note the colour key next to each return value):

![image](https://user-images.githubusercontent.com/4328790/184102056-a0dfc610-66c7-4021-9aa2-ac45525af788.png)

When the return value is the same state as the one the state machine is currently in, we can think of this as an "implied" edge that loops back around onto the same vertex.

Let's take a look at the `Tick` function that you've written for your new `SpeakerMuteState`:

```c++
MotorStateId const Tick(unsigned long const)
{
    IrPacket packet;
    if (irReceiver.TryGetPacket(packet) && !packet.IsRepeat)
    {
        if (packet.Code == config.MuteCode) return MUTE;
    }
    return MUTE;
}
```

Essentially, you've built this state machine:

![image](https://user-images.githubusercontent.com/4328790/184100932-b594c850-736b-44a9-a711-dd6c311f8c46.png)

Because you haven't modified any of the existing states' `Tick` functions to return `MUTE`, there's no way to ever enter the muted state. Additionally, because your `SpeakerMuteState`'s Tick function never returns anything other than `MUTE`, there's no way to ever *leave* the mute state once you get there.

Hopefully this should give you enough info to figure out what changes you need to make here.
